spring.application.name=springboot_backend

employee.storage.type=csv
employee.csv.file=data/employees.csv

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration,org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
spring.data.jpa.repositories.enabled=false